name: Deploy Node.js App on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t f1-relay .

      - name: Stop & Remove Old Container
        run: |
          docker stop f1-relay || true
          docker rm f1-relay || true

      - name: Run New Container
        run: |
          docker run -d \
            --name f1-relay \
            -p 3333:3333 \
            -p 20777:20777/udp \
            --restart unless-stopped \
            f1-relay
